config/routes.rb
Realiser::Engine.routes.draw do
  namespace :web do
    resources :settings
  end
  root to: 'web/settings#index'
end

app/models/realiser/application_record.rb
module Realiser
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/realiser/setting.rb
module Realiser
  # The Realiser Setting
  class Setting < Realiser::ApplicationRecord
    validates :key, uniqueness: { case_sensitive: false }, presence: true
    validates :value, presence: true

    def self.[](key)
      find_by(key: key).try(:value)
    end
  end
end

app/controllers/realiser/application_controller.rb
module Realiser
  class ApplicationController < ActionController::Base
  end
end

app/controllers/realiser/web/application_controller.rb
module Realiser
  module Web
    class ApplicationController < Realiser::ApplicationController
    end
  end
end

app/controllers/realiser/web/settings_controller.rb
module Realiser
  module Web
    class SettingsController < Realiser::Web::ApplicationController
      def index
        @settings = Realiser::Setting.all
      end

      def new
        @setting = Realiser::Setting.new
      end

      def show
        @setting = Realiser::Setting.find_by(id: params[:id])
      end

      def edit
        @setting = Realiser::Setting.find_by(id: params[:id])
      end

      # rubocop:disable Style/RedundantArgument
      def update
        setting = Realiser::Setting.find_by(id: params[:id])
        if setting.update(form_params)
          flash[:success] = 'Successfully to update the setting'
          return redirect_to web_setting_path(setting)
        end
        flash.now[:danger] = setting.errors.full_messages.join('')
        render :edit
      end
      # rubocop:enable Style/RedundantArgument

      def destroy
        setting = Realiser::Setting.find_by(id: params[:id])
        setting.destroy!
        flash[:success] = 'Successfully deleted the setting'
        redirect_to root_path
      end

      def create
        @setting = Realiser::Setting.new(form_params)
        if @setting.invalid?
          flash.now[:danger] = @setting.errors.full_messages.join(', ')
          return render :new
        end
        @setting.save!
        flash[:success] = 'Succesfully created a new setting'
        redirect_to root_path
      end

      private

      def form_params
        params.require(:setting).permit(:key, :value)
      end
    end
  end
end

app/helpers/realiser/application_helper.rb
module Realiser
  module ApplicationHelper
  end
end

app/views/layouts/realiser/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Realiser</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "realiser/application", media: "all" %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-4">
        <nav class="navbar navbar-light bg-light">
          <div class="container-fluid">
            <%= link_to 'Realiser', root_path, class: 'navbar-brand' %>
          </div>
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/realiser/web/settings/edit.html.erb
<div class="card">
  <div class="card-header">
    Edit Setting #<%= @setting.id %> 
  </div>
  <div class="card-body">
    <%= render 'shared/message' %>

    <%= form_with(model: @setting, url: web_setting_path(@setting), method: :put) do |form| %>
      <div class="form-group row">
        <div class="col-6">
          <div class="mb-3">
            <%= form.label :key, class: 'form-label fw-bold' %>
            <%= form.text_field :key, class: 'form-control', autocomplete: 'off', required: true %>
          </div>
        </div>
        <div class="col-6">
          <div class="mb-3">
            <%= form.label :value, class: 'form-label fw-bold' %>
            <%= form.text_field :value, class: 'form-control', autocomplete: 'off', required: true %>
          </div>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-12">
          <%= form.submit 'Update', class: 'btn btn-primary' %>
          <%= link_to 'Back', web_setting_path(@setting), class: 'btn btn-default' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/realiser/web/settings/index.html.erb
<%= render 'shared/message' %>

<div class="row">
  <div class="col-md-12 mb-4">
    <%= link_to 'Create new setting', new_web_setting_path, class: 'btn btn-secondary d-block' %>
  </div>
</div>

<% if @settings.present? %>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Key</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <% @settings.each.with_index(1) do |setting, index| %>
        <tr>
          <td><%= link_to index, web_setting_path(setting) %></td>
          <td><%= setting.key %></td>
          <td><%= setting.value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>The settings was blank, try add a new one in <%= link_to 'here', new_web_setting_path %>.</p>
<% end %>
   

app/views/realiser/web/settings/new.html.erb
<div class="card">
  <div class="card-header">
    Create a new setting 
  </div>
  <div class="card-body">
    <%= render 'shared/message' %>

    <%= form_with(model: @setting, url: web_settings_path, method: :post) do |form| %>
      <div class="form-group row">
        <div class="col-6">
          <div class="mb-3">
            <%= form.label :key, class: 'form-label fw-bold' %>
            <%= form.text_field :key, class: 'form-control', autocomplete: 'off', required: true %>
          </div>
        </div>
        <div class="col-6">
          <div class="mb-3">
            <%= form.label :value, class: 'form-label fw-bold' %>
            <%= form.text_field :value, class: 'form-control', autocomplete: 'off', required: true %>
          </div>
        </div>      </div>

      <div class="form-group row">
        <div class="col-md-12">
          <%= form.submit 'Create new setting', class: 'btn btn-primary' %>
          <%= link_to 'Back', root_path, class: 'btn btn-default' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/realiser/web/settings/show.html.erb
<%= render 'shared/message' %>

<div class="d-flex justify-content-between">
  <h4>Setting #<%= @setting.id %></h4>
  <%= button_to 'Destroy', web_setting_path(@setting),
                         method: :delete,
                         class: 'btn btn-danger' %>
</div>

<table class="table">
  <tr>
    <th class="w-20">Key</th>
    <td class="w-80"><%= @setting.key %></td>
  </tr>
  <tr>
    <th>Value</th>
    <td><%= @setting.value %></td>
  </tr>
  <tr>
    <th>Created At</th>
    <td><%= @setting.created_at %></td>
  </tr>
  <tr>
    <th>Updated At</th>
    <td><%= @setting.updated_at %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_web_setting_path(@setting), class: 'btn btn-info px-4' %>
<%= link_to 'Back', web_settings_path, class: 'btn btn-default px-4' %>

app/views/shared/_message.html.erb
<% if flash.any? %>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert">
      <%= value %>
    </div>
  <% end %>
<% end %>